services:
  api:
    build: .
    container_name: nexusml_api_${MODEL_ID}
    ports:
      - "8001:8000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - MODEL_NAME=${MODEL_FILE_NAME}

  redis:
    image: redis:7-alpine
    container_name: nexusml_redis
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:v2.50.0
    container_name: nexusml_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api

  grafana:
    image: grafana/grafana:10.3.3
    container_name: nexusml_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning

volumes:
  grafana_data: